name: Summary CI
on:
  schedule:
    - cron: "0 0 * * *"
  repository_dispatch:
    types: [summary]
  workflow_dispatch:
jobs:
  release:
    name: Generate README
    runs-on: ubuntu-latest
    steps:
      - name: Generate README
        uses: upptime/uptime-monitor@v1
        with:
          command: "readme"
        env:
          GH_PAT: ${{ secrets.GH_PAT || secrets.GITHUB_TOKEN }}
