name: Updates CI
on:
  schedule:
    - cron: "0 3 * * *"
  repository_dispatch:
    types: [updates]
  workflow_dispatch:
jobs:
  release:
    name: Run updates
    runs-on: ubuntu-latest
    steps:
      - name: Run updates
        uses: upptime/uptime-monitor@v1.41.3
        with:
          command: "update-template"
        env:
          GH_PAT: ${{ secrets.GH_PAT || secrets.GITHUB_TOKEN }}
